language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirement.txt
before_script:
  - python manage.py migrate
# command to run tests
script: 
  - black --check .
  - flake8 .
  - coverage run --source=polls manage.py test
after_script: 
  - coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: "us-east-2"
  app: "mysite"
  env: "mysite-dev"