language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
# before_script:
#   - python3 manage.py migrate
# command to run tests
script: 
  - black --check .
  - flake8 --extend-ignore E501,F401 .
  - coverage run --source=polls manage.py test
after_script: 
  - coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: 
    secure: $SECRETACCESSKEY
  region: "us-east-2"
  app: "mysite"
  env: "mysite-dev"
  on:
    repo: jazwu/mysite
    branch: main
  skip_cleanup: 'true'