language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirement.txt
# command to run tests
script: pytest
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: "us-east-2"
  app: "mysite"
  env: "mysite-dev"